---
title: "Time sync check"
output: html_notebook
---

## Load libraries

```{r message=FALSE, warning=FALSE}
library(bioacoustics)
library(tuneR)
library(seewave)
library(dplyr)
library(tidyverse)
library(lubridate)
library(tools)
library(ggplot2)
library(ggpmisc)
library(plotly)
ymd_hms = function(dt) {
  lubridate::ymd_hms(dt, tz="Pacific/Auckland")
}
```

## Load RFID log files

```{r}
files = list.files("data/2019 RFID", pattern = "*.TXT$", recursive = TRUE, full.names=TRUE)
csvs = lapply(files, function(path) {
  csv = read.csv(path, header=FALSE, col.names = c("year", "month", "day", "hour","minute_sec", "id", "ext", "int", "msg"))
  csv$site = strsplit(strsplit(path, "/")[[1]][4], "_")[[1]][1]
  csv
})
rfid = do.call(rbind, csvs)
rfid$datetime = paste0(rfid$year, "-", rfid$month, "-", rfid$day, " ", rfid$hour, ":", rfid$minute_sec)
rfid$datetime = ymd_hms(rfid$datetime)
ggplot(rfid, aes(datetime)) +
  geom_freqpoly(binwidth = 60 * 60)
```
### Reference spectrograms for playback files
```{r}
html_tag_audio <- function(file, type = c("wav")) {
  type <- match.arg(type)
  htmltools::tags$audio(
    controls = "",
    htmltools::tags$source(
      src = file,
      type = glue::glue("audio/{type}", type = type)
    )
  )
}
files = Sys.glob("./clips/PB*.wav")
setNames(lapply(files, html_tag_audio), files)
```

```{r}
PB_wavs = lapply(files, function(f) {
  wav = read_audio(f)
  wav_length = round(length(wav) / wav@samp.rate, 2)
  spectro(wav, main=paste0(basename(f), " ", wav_length, "s"), osc=TRUE)
  data.frame(filename=basename(f), wav_length, stringsAsFactors = FALSE)
})
PB_wavs = do.call(rbind, PB_wavs)
```

### Build a reference dataframe showing which wave files correspond to which times

```{r}
files = list.files("data/2019 BAR recordings", pattern = "*.wav$", recursive = TRUE, full.names=TRUE)
library(pbapply)
df = pblapply(files, function(f) {
  bits = strsplit(basename(f), "_")[[1]]
  start = ymd_hms(paste(bits[2], bits[3]))
  site = strsplit(f, "/")[[1]][4]
  try({
    wav_header = readWave(f, header=TRUE)
    duration = wav_header$samples / wav_header$sample.rate
    end = start + duration
    return(data.frame(filename = f, base_filename = basename(f), site = site, start = start, end = end, interval = interval(start, end), stringsAsFactors = FALSE))
  })
  NULL
})
df = do.call(rbind, df)
df[c("site", "interval")]
```


### Select a few playback entries to check

```{r}
PB_to_check = "PB0024.wav"
filtered_rfid = filter(rfid, msg == PB_to_check)
filtered_rfid$corrected_datetime = filtered_rfid$datetime
filtered_rfid$match = lapply(1:nrow(filtered_rfid), function(i) {
  dt = filtered_rfid$corrected_datetime[i]
  site = filtered_rfid$site[i]
  indices = which(dt %within% df$interval[df$site == site,])
  if (length(indices) == 0) indices = NA
  indices
})
print(paste("There are", nrow(filtered_rfid), PB_to_check, "playbacks, of which", sum(!is.na(filtered_rfid$match)), "have recordings"))
# A few randomly
#datetimes_to_check = sort(sample(filtered_rfid$datetime[!is.na(filtered_rfid$match)], 10))
# Ones from the 13th
#datetimes_to_check = filtered_rfid$datetime[!is.na(filtered_rfid$match) & filtered_rfid$datetime < ymd("2019-12-14")]
datetimes_to_check = filtered_rfid$corrected_datetime[!is.na(filtered_rfid$match) & filtered_rfid$corrected_datetime %within% interval(ymd_hms("2019-12-03 06:45:00"), ymd_hms("2019-12-03 07:32:00"))]
print(datetimes_to_check)
```

```{r}
#dt = ymd_hms("2019-12-13 16:45:04")
checked_clips = lapply(datetimes_to_check, function(dt) {
  match = filtered_rfid$match[filtered_rfid$corrected_datetime == dt]
  f = df$filename[match]
  clip_start = time_length(dt - df$start[match], unit = "seconds")
  clip_end = clip_start + PB_wavs$wav_length[PB_wavs$filename == PB_to_check]
  print(paste(f, dt, clip_start, clip_end))
  wav = read_audio(f, from = clip_start, to = clip_end + 1)
  spectro(wav, main=dt, osc=TRUE)
  play(wav)
  wav
})
```

## Compare annotations with nearest RFID log

```{r}
annotations = lapply(list.files("misc", "*.txt", full.names=TRUE), read.table, sep="\t", header=TRUE, stringsAsFactors = FALSE)
annotations = do.call(rbind, annotations)
annotations$datetime = ymd_hms(paste(annotations$Begin.Date, annotations$Begin.Clock.Time))
annotations$offset = rep(NA, nrow(annotations))
annotations$offset_from_start_of_recording = rep(NA, nrow(annotations))
annotations$Individual.ID[annotations$Individual.ID == "PB0009" | annotations$Individual.ID == "PB009"] = "PB0009zp"
for (i in 1:nrow(annotations)) {
  if (substring(annotations$Individual.ID[i], 0, 2) == "PB") {
    filtered_datetimes = rfid$datetime[annotations$Nest.ID[i] == rfid$site & rfid$msg == paste0(annotations$Individual.ID[i], ".wav")]
    matched_rec_start = df$start[df$site == annotations$Nest.ID[i] & annotations$datetime[i] %within% df$interval]
    if (length(matched_rec_start) == 1) {
      annotations$offset_from_start_of_recording[i] = time_length(annotations$datetime[i] - matched_rec_start)
    }
    diffs = time_length(filtered_datetimes - annotations$datetime[i])
    offset = diffs[which.min(abs(diffs))]
    if (length(offset) == 1) {
      annotations$offset[i] = offset
    }
  }
}
filtered_annotations = annotations[!is.na(annotations$offset) & abs(annotations$offset) < 60 & annotations$Nest.ID != "NNK35",]
ggplot(data = filtered_annotations, aes(x=offset_from_start_of_recording, y=offset, color=Nest.ID)) +
    geom_point() +
    geom_smooth(method = "lm") + 
    stat_poly_eq(formula = y ~ x,
                   aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                   parse = TRUE)
```



